"""extract — geometric extraction of a bank-statement PDF into the bronze Parquet layer.

A faithful port of the validated prototype `parse_releves.parse_pdf` (Bank): extract
words with x-coordinates via pdfplumber, classify each into a column by horizontal position, and rebuild
one transaction per line carrying a `date_comptable` (continuations extend the `libelle`). The RAW `libelle`
is kept here — anonymization happens downstream in build-silver, so bronze is a faithful, immutable record.

funcd wiring:
  * runtime  python314 (stock); pdfplumber + pyarrow travel in the ADR-0089 bundle.
  * spec.blob `landing` (read) → the dropped PDF;  `bronze` (write, owner) → the Parquet output.
  * spec.config `releve-project-config` → STOP_KEYWORDS / BANK via env.
  * input `{ file: <object-key> }` is the landed key projected by the Sensor (${{ event.data.key }}).

Reads/writes go through `context.blob` (ADR-0127) — the native, binding-gated blob accessor over the
worker-node local API: no S3 keypair, no boto3. The PDF is fetched as raw bytes (`context.blob.get`), the
Parquet is written back (`context.blob.put`); the same `spec.blob` bindings authorize each access.
"""

from __future__ import annotations

import io
import logging
import os
import re
from datetime import date
from decimal import Decimal

import pdfplumber
import pyarrow as pa
import pyarrow.parquet as pq
from funcd_shim import CloudEvent, FunctionContext

# FuncInput/FuncOutput are generated by `funcdctl types` from the funcdctl.yaml contract
# (funcd_types.py — DO NOT EDIT); the single source, never redefined here.
from funcd_types import FuncInput, FuncOutput

DATE_RE = re.compile(r"^\d{2}\.\d{2}\.\d{2}$")
AMT_FRAG_RE = re.compile(r"^\d{1,3}(,\d{2})?$")

# Structural (non-transaction) lines whose amounts must NOT bleed into the current transaction: the
# balance lines (ANCIEN/NOUVEAU SOLDE) and the printed operations total, plus header markers. A
# dateless line is otherwise treated as a libellé/amount continuation, so these must flush-and-skip.
# Kept consistent with verify's SKIP set (the two parsers must agree on what is a transaction).
STRUCTURAL_SKIP = (
    "TOTALDESOPERATIONS", "SOLDE", "PERIODE", "RELEVE", "TITULAIRE", "IBAN", "NATUREDESOPERATIONS",
)

# Column x-bounds (Bank geometry) — the prototype's constants.
X_DATE_MIN, X_DATE_MAX = 48, 100
X_LIB_MIN, X_LIB_MAX = 100, 335
X_VAL_MIN, X_VAL_MAX = 335, 400
X_AMT_MIN = 400
X_DEBIT_CREDIT_SPLIT = 500


def _stop_keywords() -> tuple[str, ...]:
    """Header/footer/balance/account markers to skip — from the ConfigMap, so the real account number
    (PII) lives in config, not code (STOP_KEYWORDS, ADR-0057)."""
    raw = os.environ.get("STOP_KEYWORDS", "")
    return tuple(k.strip() for k in raw.split(",") if k.strip())


def _iso_date(d: str) -> str:
    dd, mm, yy = d.split(".")
    return f"{2000 + int(yy)}-{mm}-{dd}"


def _group_lines(words, ytol=4):
    words = sorted(words, key=lambda w: w["top"])
    lines, cur, cur_top = [], [], None
    for w in words:
        if cur_top is None or abs(w["top"] - cur_top) <= ytol:
            cur.append(w)
            cur_top = w["top"] if cur_top is None else cur_top
        else:
            lines.append(cur)
            cur, cur_top = [w], w["top"]
    if cur:
        lines.append(cur)
    for ln in lines:
        ln.sort(key=lambda w: w["x0"])
    return lines


def _extract_amount(line):
    frags = [w for w in line if w["x0"] >= X_AMT_MIN and AMT_FRAG_RE.match(w["text"])]
    if not frags:
        return None, None
    frags.sort(key=lambda w: w["x0"])
    value = "".join(w["text"] for w in frags).replace(" ", "").replace(",", ".")
    is_credit = max(w["x1"] for w in frags) >= X_DEBIT_CREDIT_SPLIT
    return value, is_credit


def _parse_pdf(pdf_bytes: bytes, stop: tuple[str, ...]) -> list[dict]:
    transactions: list[dict] = []
    cur: dict | None = None

    def flush():
        nonlocal cur
        if cur is not None:
            cur["libelle"] = " ".join(cur["libelle"]).strip()
            transactions.append(cur)
            cur = None

    def is_stop(line) -> bool:
        txt = "".join(w["text"] for w in line)
        return any(k and k in txt for k in stop)

    def is_structural(line) -> bool:
        txt = "".join(w["text"] for w in line).upper().replace(" ", "")
        return any(k in txt for k in STRUCTURAL_SKIP)

    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        for page in pdf.pages:
            for line in _group_lines(page.extract_words(x_tolerance=1, y_tolerance=3)):
                if is_stop(line) or is_structural(line):
                    flush()
                    continue
                date_word = next(
                    (w for w in line if X_DATE_MIN <= w["x0"] < X_DATE_MAX and DATE_RE.match(w["text"])), None
                )
                lib_words = [w["text"] for w in line if X_LIB_MIN <= w["x0"] < X_LIB_MAX]
                val_word = next(
                    (w for w in line if X_VAL_MIN <= w["x0"] < X_VAL_MAX and DATE_RE.match(w["text"])), None
                )
                amount, is_credit = _extract_amount(line)
                if date_word:
                    flush()
                    cur = {
                        "date_comptable": _iso_date(date_word["text"]),
                        "date_valeur": _iso_date(val_word["text"]) if val_word else "",
                        "libelle": list(lib_words),
                        "debit": "",
                        "credit": "",
                    }
                    if amount is not None:
                        cur["credit" if is_credit else "debit"] = amount
                elif cur is not None:
                    if lib_words:
                        cur["libelle"].extend(lib_words)
                    if amount is not None:
                        if is_credit and not cur["credit"]:
                            cur["credit"] = amount
                        elif not is_credit and not cur["debit"]:
                            cur["debit"] = amount
        flush()
    return transactions


# Bronze is the first STRUCTURED layer (the raw copy is the landing/ PDF), so it carries real types:
# date32 for the dates, decimal128(12,2) for the amounts. decimal128 is EXACT — same no-float-rounding
# guarantee the decimal strings gave, but with the correct type. libelle stays string (it is text).
_BRONZE_SCHEMA = pa.schema(
    [
        ("date_comptable", pa.date32()),
        ("date_valeur", pa.date32()),               # nullable — empty on the source ⇒ null
        ("libelle", pa.string()),
        ("debit", pa.decimal128(12, 2)),
        ("credit", pa.decimal128(12, 2)),
        ("montant", pa.decimal128(12, 2)),
    ]
)


def _to_parquet(txs: list[dict]) -> bytes:
    def amt(s: str) -> Decimal:
        return Decimal(s) if s else Decimal("0")

    def day(s: str) -> date | None:
        return date.fromisoformat(s) if s else None

    cols = {
        "date_comptable": [day(t["date_comptable"]) for t in txs],
        "date_valeur": [day(t["date_valeur"]) for t in txs],
        "libelle": [t["libelle"] for t in txs],
        "debit": [amt(t["debit"]) for t in txs],
        "credit": [amt(t["credit"]) for t in txs],
        "montant": [amt(t["credit"]) - amt(t["debit"]) for t in txs],
    }
    buf = io.BytesIO()
    pq.write_table(pa.table(cols, schema=_BRONZE_SCHEMA), buf)
    return buf.getvalue()


def handle(context: FunctionContext, event: CloudEvent[FuncInput]) -> FuncOutput:
    """Parse EVERY PDF in landing/ → bronze/<stem>.parquet (bronze is 1:1 with a source statement). Takes
    NO input; returns a run summary (statement count + total debit/credit across all)."""
    stop = _stop_keywords()
    keys = sorted(k for k in context.blob.list("landing", "") if k.lower().endswith(".pdf"))
    if not keys:
        raise ValueError("extract: no .pdf objects in landing/ to process")

    total_debit = Decimal("0")
    total_credit = Decimal("0")
    for key in keys:
        pdf_bytes = context.blob.get("landing", key)
        if pdf_bytes is None:
            raise ValueError(f"extract: object landing/{key!r} disappeared mid-run")
        txs = _parse_pdf(pdf_bytes, stop)
        if not txs:
            raise ValueError(f"extract: no transactions in {key!r} (bad geometry / wrong bank profile?)")
        stem = os.path.splitext(os.path.basename(key))[0]
        context.blob.put("bronze", f"{stem}.parquet", _to_parquet(txs))
        total_debit += sum((Decimal(t["debit"]) for t in txs if t["debit"]), Decimal("0"))
        total_credit += sum((Decimal(t["credit"]) for t in txs if t["credit"]), Decimal("0"))
    logging.info("extract: parsed %d statement(s) → bronze (debit=%s credit=%s)",
                 len(keys), total_debit, total_credit)
    return {"statements": len(keys), "debit": str(total_debit), "credit": str(total_credit)}
