# Generated by `funcdctl types` (ADR-0122) — DO NOT EDIT.
# DX-only: the platform never trusts these types; they drive editor autocomplete.
from __future__ import annotations
from typing import Literal, TypedDict

FuncInput = dict[str, object]  # non-record contract side

class FuncOutput(TypedDict):
    rows: int
    silver: str

class Bindings:
    blob: Literal["bronze", "silver", "reports"]
