"""build-silver — GATE 2 (PII) + conform. Faithful port of the prototype `anonymize.py` plus the silver
typing/dedup step from the platform ROADMAP (Phase 3).

Reads the WHOLE bronze layer (all statements — needed for cross-statement dedup of overlapping periods),
scrubs ONLY the `libelle` column (all numeric/date columns are untouched, byte-for-byte), runs a residual
scan that RAISES if any sensitive pattern survives (the blocking PII gate — anonymization precedes every
downstream read), types the columns, deduplicates overlapping statements, and writes the conformed
`silver/transactions.parquet`. Silver is Parquet; the DuckLake marts live in gold (managed by the `lake`
catalog).

funcd wiring: spec.blob `bronze` (read all) + `silver` (write, owner), through `context.blob` (ADR-0127) —
no S3 keypair, no httpfs. Each bronze Parquet is fetched as bytes and registered as an in-memory Arrow
table for DuckDB to conform over; the conformed silver Parquet is written back with `context.blob.put`.
"""

from __future__ import annotations

import io
import logging
import re

import duckdb
import pyarrow as pa
import pyarrow.parquet as pq
from funcd_shim import CloudEvent, FunctionContext

# FuncInput/FuncOutput are generated by `funcdctl types` from the funcdctl.yaml contract
# (funcd_types.py — DO NOT EDIT); the single source, never redefined here.
from funcd_types import FuncInput, FuncOutput

# Patterns that MUST NOT survive anonymization (the prototype's residual-control set, account-number-free).
RESIDUAL = [
    (re.compile(r"\b\d{16}\b"), "16-digit sequence"),
    (re.compile(r"\b[0-9A-Fa-f]{16,}\b"), "long hash/reference"),
    (re.compile(r"FR\d{2}ZZZ"), "creditor id (ICS)"),
    (re.compile(r"\bFR\d{11}\b"), "VAT number"),
]


def _scrub_long(text: str) -> str:
    """Any long alphanumeric token (>=8) carrying >=4 digits → [REF]."""
    def repl(m: re.Match[str]) -> str:
        tok = m.group(0)
        return "[REF]" if sum(c.isdigit() for c in tok) >= 4 else tok

    return re.sub(r"[0-9A-Za-z]{8,}", repl, text)


def _anonymize(lib: str) -> str:
    s = lib
    s = re.sub(r"0*\d{4}[0-9X]{8}\d{4}", "****CARD", s)          # card PAN (masked/full/leading zeros)
    s = re.sub(r"(/BEN ).*?( /REF)", r"\1BENEFICIAIRE\2", s)      # transfer beneficiary
    s = re.sub(r"(/REFDO)\s*[0-9A-Fa-f]{12,}", r"\1", s)          # transfer reference
    s = re.sub(r"\bM\.\s*[A-Z]{1,4}(?:\s+[A-Z]{1,4})?\b", "M. [NOM]", s)
    s = re.sub(r"\bTRF\w+", "[REF]", s)
    s = re.sub(r"ID EMETTEUR/\S+", "ID EMETTEUR/[ICS]", s)
    s = re.sub(r"\bMDT/\S+", "MDT/[REF]", s)
    s = re.sub(r"\bREF/\S+", "REF/[REF]", s)
    s = re.sub(r"FR\d{2}ZZZ\w*", "[ICS]", s)
    s = _scrub_long(s)
    return re.sub(r"\s{2,}", " ", s).strip()


def _conform(context: FunctionContext, con: duckdb.DuckDBPyConnection) -> list[dict]:
    """Type + dedup the WHOLE bronze layer. Reads every bronze Parquet via context.blob (ADR-0127) into
    one in-memory Arrow table, registers it, and lets DuckDB conform over it. Overlapping statements share
    transactions, so dedup on the business key (date/amount/raw-libelle), keeping one — the ROADMAP's
    GROUP-BY-ALL rebuild. No httpfs, no S3 keypair: the binding is the grant."""
    tables = []
    for key in context.blob.list("bronze", ""):
        if not key.endswith(".parquet"):
            continue
        data = context.blob.get("bronze", key)
        if data is not None:
            tables.append(pq.read_table(io.BytesIO(data)))
    if not tables:
        return []
    con.register("bronze_all", pa.concat_tables(tables))
    # Bronze already carries the real types (date32 dates, decimal128 amounts), so silver INHERITS them —
    # no casts needed. Silver's job here is dedup: collapse rows duplicated by overlapping statements.
    rows = con.execute(
        """
        SELECT date_comptable,
               date_valeur,
               libelle,
               debit,
               credit,
               montant
        FROM bronze_all
        GROUP BY ALL                       -- collapse duplicated rows from overlapping statements
        ORDER BY date_comptable, montant
        """
    ).fetchall()
    cols = [d[0] for d in con.description]
    return [dict(zip(cols, r, strict=False)) for r in rows]


def handle(context: FunctionContext, event: CloudEvent[FuncInput]) -> FuncOutput:
    """bronze/*.parquet → anonymize + gate + conform → silver/transactions.parquet."""
    con = duckdb.connect()
    conformed = _conform(context, con)

    residual_hits: list[str] = []
    for r in conformed:
        r["libelle"] = _anonymize(r["libelle"])
        for rx, label in RESIDUAL:
            if rx.search(r["libelle"]):
                residual_hits.append(f"{label}: {r['libelle']}")
    if residual_hits:
        hits = "\n  - ".join(residual_hits[:10])
        raise ValueError(f"build-silver PII GATE failed — residual sensitive data:\n  - {hits}")

    table = pa.Table.from_pylist(conformed)
    buf = io.BytesIO()
    pq.write_table(table, buf)
    context.blob.put("silver", "transactions.parquet", buf.getvalue())
    logging.info("build-silver: conformed %d transaction(s) → silver/transactions.parquet", len(conformed))
    return {"silver": "transactions.parquet", "rows": len(conformed)}
