"""to-gold — build the business marts in the gold DuckLake layer by driving the `lake` catalog over Quack.

Mirrors examples/catalog-quack/consumer.py, but runs a WRITE statement: it sends the project's mart
SQL (mart_depenses_mensuelles.sql) to the CatalogService, which reads the conformed `silver` Parquet (its
own binding) and persists the result as a DuckLake table under gold/ (the catalog is gold's owner/writer —
ADR-0087, so no gold write-binding is needed here). The catalog's Quack endpoint + token are injected by the
`spec.catalogs: [lake]` consumer binding as FUNCD_CATALOG_LAKE_URL / _TOKEN (ADR-0091).
"""

from __future__ import annotations

import logging
import os

import duckdb
from funcd_shim import CloudEvent, FunctionContext

# FuncInput/FuncOutput are generated by `funcdctl types` from the funcdctl.yaml contract
# (funcd_types.py — DO NOT EDIT); the single source, never redefined here.
from funcd_types import FuncInput, FuncOutput

# The mart SQL travels in the bundle next to the handler (build.py copies functions/to_gold/*.sql in).
_SQL_PATH = os.path.join(os.path.dirname(__file__), "mart_depenses_mensuelles.sql")


def _quack_uri(endpoint: str) -> str:
    return endpoint if endpoint.startswith("quack://") else "quack://" + endpoint


def _load_ext(con: duckdb.DuckDBPyConnection) -> None:
    """Load the quack extension OFFLINE from the bundle's duckdb-ext/ (ADR-0089) — no network install."""
    bundle_dir = os.environ.get("FUNCD_BUNDLE_DIR")
    ext_dir = os.environ.get("DUCKDB_EXTENSION_DIRECTORY")
    if not ext_dir and bundle_dir and os.path.isdir(os.path.join(bundle_dir, "duckdb-ext")):
        ext_dir = os.path.join(bundle_dir, "duckdb-ext")
    if ext_dir:
        con.execute(f"SET extension_directory='{ext_dir}';")
    con.execute("LOAD quack;")


def handle(context: FunctionContext, event: CloudEvent[FuncInput]) -> FuncOutput:
    """Run the mart SQL on the `lake` catalog over Quack; the catalog persists the DuckLake gold table."""
    url = os.environ["FUNCD_CATALOG_LAKE_URL"]
    token = os.environ["FUNCD_CATALOG_LAKE_TOKEN"]
    with open(_SQL_PATH, encoding="utf-8") as f:
        mart_sql = f.read()

    con = duckdb.connect()
    _load_ext(con)
    uri = _quack_uri(url)
    # Quack is DuckDB-to-DuckDB (Protobuf over HTTP): quack_query runs SQL ON THE REMOTE catalog engine,
    # which has the DuckLake attached as the `lakehouse` catalog (the catalog owns gold; ADR-0087). A
    # served query defaults to the engine's `memory` catalog, so target `lakehouse` explicitly: `USE
    # lakehouse` (persists within this one multi-statement call) makes the mart DDL land there, and
    # `CHECKPOINT` flushes the DuckLake's Parquet to gold/. disable_ssl: the engine serves plain HTTP.
    con.execute(
        "SELECT * FROM quack_query(?, ?, disable_ssl := true, token := ?)",
        [uri, f"USE lakehouse;\n{mart_sql}\nCHECKPOINT lakehouse;", token],
    )
    rows = con.execute(
        "SELECT * FROM quack_query(?, ?, disable_ssl := true, token := ?)",
        [uri, "SELECT count(*) FROM lakehouse.main.mart_depenses_mensuelles", token],
    ).fetchone()[0]
    logging.info("to-gold: mart_depenses_mensuelles — %s month(s)", rows)
    return {"gold": "mart_depenses_mensuelles", "rows": rows}
