"""verify — GATE 1: an INDEPENDENT cross-check of the bronze extraction, faithful port of the prototype
`verify_independent.py` (+ the printed-total checks from `run_all.py`).

It does NOT reuse the geometric parser. It re-extracts every transaction a different way — the last token of
each raw-text line for the amount/date, and a SEMANTIC rule on the libelle for the debit/credit sense — then
reconciles line-by-line against `extract`'s bronze Parquet, and against the statement's PRINTED totals
(`TOTAL DES OPERATIONS`). Two independent methods agreeing (and matching the bank's own printed figures) is
the trust signal. ANY discrepancy → raise → the run fails BEFORE the data is conformed. No write.

funcd wiring: spec.blob `landing` (read PDF) + `bronze` (read the Parquet to reconcile). Both read-only,
through `context.blob` (ADR-0127) — no S3 keypair, no boto3.
"""

from __future__ import annotations

import io
import logging
import os
import re
from decimal import Decimal
from typing import Any

import pdfplumber
import pyarrow.parquet as pq
from funcd_shim import CloudEvent, FunctionContext

# FuncInput/FuncOutput are generated by `funcdctl types` from the funcdctl.yaml contract
# (funcd_types.py — DO NOT EDIT); the single source, never redefined here.
from funcd_types import FuncInput, FuncOutput

DATE_START = re.compile(r"^(\d{2})\.(\d{2})\.(\d{2})\s")
AMT = re.compile(r"^\d[\d]*,\d{2}$")
AMT_IN_TEXT = re.compile(r"\d[\d ]*,\d{2}")
SKIP = ("TOTALDESOPERATIONS", "Solde", "PERIODE", "RELEVE", "Titulaire")


def _iso(dd: str, mm: str, yy: str) -> str:
    return f"20{yy}-{mm}-{dd}"


def _classify(libelle: str) -> str | None:
    """Debit/credit sense from the operation TYPE — independent of geometry."""
    u = libelle.upper().replace(" ", "")
    if u.startswith("REMBOURST"):
        return "credit"
    if "RECU" in u and "VIR" in u:
        return "credit"
    if "EMIS" in u and "VIR" in u:
        return "debit"
    if u.startswith("FACTURE(S)CARTE") or u.startswith("DU") or u.startswith("RETRAIT"):
        return "debit"
    if "PRLV" in u or "COMMISSION" in u or "INTERET" in u:
        return "debit"
    return None


def _independent(pdf_bytes: bytes) -> list[dict[str, Any]]:
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        lines: list[str] = []
        for p in pdf.pages:
            lines += (p.extract_text() or "").splitlines()
    txs: list[dict[str, Any]] = []
    for raw in lines:
        s = raw.strip()
        if not s:
            continue
        m = DATE_START.match(s)
        if m and not any(k in s for k in SKIP):
            toks = s.split()
            last = toks[-1]
            if not AMT.match(last):
                txs.append({"date": _iso(*m.groups()), "amount": None, "sens": None, "flag": "no-amount"})
                continue
            # Reassemble a French thousands-space amount: "1 882,33" is tokenized as "1" "882,33", so the
            # decimal token is preceded by pure-digit thousands groups. extract joins the geometric
            # fragments; the independent parser must too, or a >= 1000 amount reconciles short by the
            # thousands part. The date-valeur (dd.mm.yy, has dots) separates the libellé, so walking back
            # over bare-digit groups never eats a libellé token.
            i = len(toks) - 2
            amt_toks = [last]
            while i >= 1 and re.match(r"^\d{1,3}$", toks[i]):
                amt_toks.insert(0, toks[i])
                i -= 1
            amount = Decimal("".join(amt_toks).replace(",", "."))
            mid = toks[1 : i + 1]  # after date-comptable, up to (not including) the amount group
            if mid and re.match(r"^\d{2}\.\d{2}\.\d{2}$", mid[-1]):
                mid = mid[:-1]  # drop the date-valeur
            txs.append(
                {
                    "date": _iso(*m.groups()),
                    "amount": amount,
                    "sens": None,
                    "libelle": " ".join(mid),
                    "flag": None,
                }
            )
        elif txs and txs[-1]["flag"] is None:
            txs[-1]["libelle"] = txs[-1].get("libelle", "") + " " + s
    for t in txs:
        if t["flag"] is None:
            t["sens"] = _classify(t.get("libelle", ""))
    return txs


def _printed_totals(pdf_bytes: bytes) -> tuple[Decimal | None, Decimal | None]:
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        full = "\n".join(p.extract_text() or "" for p in pdf.pages)
    for line in full.splitlines():
        if "TOTALDESOPERATIONS" in line.replace(" ", ""):
            a = AMT_IN_TEXT.findall(line)
            d = Decimal(a[0].replace(" ", "").replace(",", ".")) if a else None
            c = Decimal(a[1].replace(" ", "").replace(",", ".")) if len(a) >= 2 else Decimal("0")
            return d, c
    return None, None


def _bronze_rows(context: FunctionContext, bronze_key: str) -> list[dict[str, Any]]:
    data = context.blob.get("bronze", bronze_key)
    if data is None:
        raise ValueError(f"verify: bronze object {bronze_key!r} not found")
    table = pq.read_table(io.BytesIO(data))
    rows = table.to_pylist()
    out = []
    for r in rows:
        # bronze is typed (ADR-0089 bundle): date_comptable is a datetime.date, debit/credit are Decimal.
        # The independent parser dates are ISO strings, so render the DATE back to isoformat to compare.
        is_debit = r["debit"] != Decimal(0)
        sens = "debit" if is_debit else "credit"
        amt = r["debit"] if is_debit else r["credit"]
        out.append({"date": r["date_comptable"].isoformat(), "amount": amt, "sens": sens})
    return out


def _reconcile(
    context: FunctionContext,
    key: str,
    pdf_bytes: bytes,
    bronze_key: str,
) -> tuple[list[str], Decimal, Decimal]:
    """Reconcile ONE statement's bronze against an independent re-parse + its printed totals. Returns the
    per-statement discrepancy messages (empty ⇒ clean) plus its debit/credit totals."""
    ind = [t for t in _independent(pdf_bytes) if t["flag"] is None]
    bronze = _bronze_rows(context, bronze_key)
    errs: list[str] = []
    if len(ind) != len(bronze):
        errs.append(f"{key}: transaction count independent={len(ind)} vs bronze={len(bronze)}")
    for i, (a, b) in enumerate(zip(ind, bronze, strict=False), 1):
        if a["date"] != b["date"]:
            errs.append(f"{key} line {i}: date {a['date']} vs {b['date']}")
        if a["amount"] != b["amount"]:
            errs.append(f"{key} line {i}: amount {a['amount']} vs {b['amount']}")
        if a["sens"] is not None and a["sens"] != b["sens"]:
            errs.append(f"{key} line {i}: sense (semantic){a['sens']} vs (geometry){b['sens']}")
    pd_, pc_ = _printed_totals(pdf_bytes)
    sd = sum((t["amount"] for t in bronze if t["sens"] == "debit"), Decimal("0"))
    scr = sum((t["amount"] for t in bronze if t["sens"] == "credit"), Decimal("0"))
    if pd_ is not None and sd != pd_:
        errs.append(f"{key}: total debit computed={sd} vs printed={pd_}")
    if pc_ is not None and scr != pc_:
        errs.append(f"{key}: total credit computed={scr} vs printed={pc_}")
    return errs, sd, scr


def handle(context: FunctionContext, event: CloudEvent[FuncInput]) -> FuncOutput:
    """Reconcile EVERY bronze against an independent re-parse of its landing PDF + the printed totals. Takes
    NO meaningful input (it receives extract's summary, ignored); raises on ANY discrepancy across all."""
    bronze_keys = sorted(k for k in context.blob.list("bronze", "") if k.endswith(".parquet"))
    if not bronze_keys:
        raise ValueError("verify: no bronze/*.parquet to reconcile")

    errs: list[str] = []
    total_debit = Decimal("0")
    total_credit = Decimal("0")
    for bronze_key in bronze_keys:
        pdf_key = os.path.splitext(bronze_key)[0] + ".pdf"
        pdf_bytes = context.blob.get("landing", pdf_key)
        if pdf_bytes is None:
            errs.append(f"{pdf_key}: landing PDF missing for bronze {bronze_key}")
            continue
        stmt_errs, sd, scr = _reconcile(context, pdf_key, pdf_bytes, bronze_key)
        errs.extend(stmt_errs)
        total_debit += sd
        total_credit += scr

    if errs:
        raise ValueError("verify GATE failed:\n  - " + "\n  - ".join(errs[:20]))
    logging.info(
        "verify: reconciled %d statement(s) — 0 discrepancies (debit=%s credit=%s)",
        len(bronze_keys),
        total_debit,
        total_credit,
    )
    return {
        "ok": True,
        "statements": len(bronze_keys),
        "debit": str(total_debit),
        "credit": str(total_credit),
    }
