# Generated by `funcdctl types` (ADR-0122) — DO NOT EDIT.
# DX-only: the platform never trusts these types; they drive editor autocomplete.
from __future__ import annotations
from typing import Literal, TypedDict

FuncInput = None  # non-record contract side

class FuncOutput(TypedDict):
    count: int
    transactions: list[dict[str, object]]

class Bindings:
    catalogs: Literal["lake"]
