"""query-transactions — read the row-level silver transactions THROUGH the `lake` catalog query engine.

Unlike a direct file read, this sends a SELECT over Quack to the CatalogService (the embedded DuckDB
engine, ADR-0091). That engine reads the conformed silver Parquet with its own S3 access and returns the
rows. It demonstrates querying a layer via the catalog query engine, not by touching the blob directly.

funcd wiring: spec.catalogs `lake` (consumer) injects FUNCD_CATALOG_LAKE_URL / _TOKEN. No blob binding —
the catalog engine does the read, using its own silver binding. Returns the top 100 transactions.
"""

from __future__ import annotations

import os

import duckdb
from funcd_shim import CloudEvent, FunctionContext

# FuncInput/FuncOutput are generated by `funcdctl types` from the funcdctl.yaml contract
# (funcd_types.py — DO NOT EDIT); the single source, never redefined here.
from funcd_types import FuncInput, FuncOutput

# The conformed silver Parquet, read by the catalog engine over its own S3 access (same path the mart uses).
_SILVER = "s3://releves/silver/transactions.parquet"
_LIMIT = 100


def _quack_uri(endpoint: str) -> str:
    return endpoint if endpoint.startswith("quack://") else "quack://" + endpoint


def _load_ext(con: duckdb.DuckDBPyConnection) -> None:
    """Load the quack extension OFFLINE from the bundle's duckdb-ext/ (ADR-0089) — no network install."""
    bundle_dir = os.environ.get("FUNCD_BUNDLE_DIR")
    ext_dir = os.environ.get("DUCKDB_EXTENSION_DIRECTORY")
    if not ext_dir and bundle_dir and os.path.isdir(os.path.join(bundle_dir, "duckdb-ext")):
        ext_dir = os.path.join(bundle_dir, "duckdb-ext")
    if ext_dir:
        con.execute(f"SET extension_directory='{ext_dir}';")
    con.execute("LOAD quack;")


def handle(context: FunctionContext, event: CloudEvent[FuncInput]) -> FuncOutput:
    """Query the top 100 silver transactions through the `lake` catalog over Quack; return them."""
    url = os.environ["FUNCD_CATALOG_LAKE_URL"]
    token = os.environ["FUNCD_CATALOG_LAKE_TOKEN"]
    con = duckdb.connect()
    _load_ext(con)
    uri = _quack_uri(url)
    sql = (
        "SELECT date_comptable, libelle, debit, credit, montant "
        f"FROM read_parquet('{_SILVER}') ORDER BY date_comptable, montant LIMIT {_LIMIT}"
    )
    rows = con.execute(
        "SELECT * FROM quack_query(?, ?, disable_ssl := true, token := ?)",
        [uri, sql, token],
    ).fetchall()
    transactions = [
        {
            "date_comptable": str(r[0]),
            "libelle": r[1],
            "debit": str(r[2]),
            "credit": str(r[3]),
            "montant": str(r[4]),
        }
        for r in rows
    ]
    return {"count": len(transactions), "transactions": transactions}
